ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = SCoop Adafruit_NFCShield_I2C Wire SoftwareSerial Wire/utility
USER_LIB_PATH = ./lib
AVRDUDE = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
include /usr/share/arduino/Arduino.mk